# Base image
FROM ubuntu:latest


# Set DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Update system and install dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    vim \
    git \
    tzdata \
    supervisor

# Create application directory
WORKDIR /home/ubuntu/app

ARG CACHEBUST=1
# Clone your application
# RUN git clone https://github.com/14790897/Nighttime-Wisdom-Star.git .
COPY . /home/ubuntu/app/

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Set up the environment variables
RUN mv .env.template .env
# Set your custom environment variables
# ENV REDIS_HOST=redis
# ENV ENV=production

# Set the timezone
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Expose necessary ports
EXPOSE 5000

# Create supervisord configuration
RUN echo "[supervisord]" > /etc/supervisor/conf.d/supervisord.conf && \
    echo "nodaemon=true" >> /etc/supervisor/conf.d/supervisord.conf && \
    echo "" >> /etc/supervisor/conf.d/supervisord.conf && \
    echo "[program:flask]" >> /etc/supervisor/conf.d/supervisord.conf && \
    echo "command=gunicorn --bind 0.0.0.0:5000 app:app" >> /etc/supervisor/conf.d/supervisord.conf && \
    echo "" >> /etc/supervisor/conf.d/supervisord.conf && \
    echo "[program:background]" >> /etc/supervisor/conf.d/supervisord.conf && \
    echo "command=python3 progress_in_back.py" >> /etc/supervisor/conf.d/supervisord.conf

# Run application using supervisord
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
