version: '3'
services:
  web:
    
    image: 14790897/nighttime-wisdom-star-2:latest
    pull_policy: if_not_present
    ports:
      - "5001:5000"
    depends_on:
      - redis
    environment:
      - ENV=${ENV}
      - start_time=${start_time}
      - end_time=${end_time}
      - amount=${amount}
      - time_zone=${time_zone}

  pandora:
    
    image: pengzhile/pandora
    pull_policy: if_not_present
    environment:
      - PANDORA_SERVER=${PANDORA_SERVER}
      - PANDORA_ACCESS_TOKEN=${PANDORA_ACCESS_TOKEN}
    ports:
      - "8008:8008"
    depends_on:
      - web

  redis:
    image: "redis:alpine"
    volumes:
      - /mydata:/data
