FROM ubuntu:latest

# Update system and install dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    vim \
    git 

# Create application directory
WORKDIR /home/ubuntu/app

# Clone your application
RUN git clone https://github.com/14790897/Nighttime-Wisdom-Star.git .

# Install Python dependencies
RUN pip install -r requirements.txt

# Set up the environment variables
RUN mv .env.template .env

# Expose necessary ports
EXPOSE 5000

# Run application
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
