version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: 14790897/nighttime-wisdom-star-2:latest
    pull_policy: if_not_present
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - pandora

  pandora:
    build:
      context: .
      dockerfile: Dockerfile.pandora
    image: 14790897/nighttime-wisdom-star-pandora-2:latest
    pull_policy: if_not_present

  redis:
    image: "redis:alpine"
