version: "3.7"

services:
  frontend:
    image: 14790897/frontend_nighttime-wisdom-star:latest
    restart: always
    ports:
      - "2345:80"
    depends_on:
      - backend

  backend:
    image: 14790897/backend_nighttime-wisdom-star:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - ENV=${ENV}
      - start_time=${start_time}
      - end_time=${end_time}
      - amount=${amount}
      - time_zone=${time_zone}
      - PANDORA_ACCESS_TOKEN=${PANDORA_ACCESS_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./output.log:/output.log
      - ./output_process.log:/output_process.log

  redis:
    image: redis:latest
    volumes:
      - /mydata:/data
    ports:
      - "6379:6379"

  pandora-next:
    image: pengzhile/pandora-next
    container_name: PandoraNext
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - ./data:/data
      - ./sessions:/root/.cache/PandoraNext