# 使用官方 Python 基础镜像
FROM python:3.8

# 设置工作目录
WORKDIR /app

# 将当前目录内容复制到容器的 /app 目录
ADD . /app

# Set up the environment variables
RUN mv .env.template .env

# 安装必要的包和supervisor
RUN pip install --no-cache-dir -r requirements.txt && apt-get update && apt-get install -y supervisor

# 设置环境变量
ENV FLASK_APP=app.py

# 对外暴露端口
EXPOSE 5001

# 添加supervisor配置
ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# 运行supervisord
CMD ["/usr/bin/supervisord"]
