version: '3.7'

services:
  vue-frontend:
    build: 
      context: ./path-to-vue-dockerfile
      dockerfile: Dockerfile
    image: vue-frontend:latest
    ports:
      - "8080:80"
    depends_on: 
      - flask-backend

  flask-backend:
    build: 
      context: ./path-to-flask-dockerfile
      dockerfile: Dockerfile
    image: flask-backend:latest
    ports:
      - "5000:5000"
    depends_on: 
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    build: 
      context: ./path-to-nginx-dockerfile
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "80:80"
    depends_on: 
      - vue-frontend
      - flask-backend
