version: '3.7'

services:
  frontend:
    build: 
      context: ./frontend  
      dockerfile: dockerfile.frontend
    image: vue-frontend:latest
    ports:
      - "8080:80"
    depends_on: 
      - backend

  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: flask-backend:latest
    ports:
      - "5000:5000"
    depends_on: 
      - redis

  redis:
    image: redis:latest
    volumes:
      - /mydata:/data
    ports:
      - "6379:6379"

  pandora:
    
    image: pengzhile/pandora
    pull_policy: if_not_present
    environment:
      - PANDORA_SERVER=${PANDORA_SERVER}
      - PANDORA_ACCESS_TOKEN=${PANDORA_ACCESS_TOKEN}
    ports:
      - "8008:8008"