version: '3.7'

services:
  frontend:
    build: 
      context: ./vuefrontend  
      dockerfile: dockerfile
    image: vue-frontend:latest
    ports:
      - "8080:80"
    depends_on: 
      - flask-backend

  backend:
    build: 
      context: ./path-to-flask-dockerfile
      dockerfile: Dockerfile
    image: flask-backend:latest
    ports:
      - "5000:5000"
    depends_on: 
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

